language: cpp
compiler: clang

before_install:
# DEPENDENCIES
  - brew update
  - brew install yaml-cpp
  - brew install boost
  - brew install lua

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

os: osx
