language: cpp
compiler: clang

before_install:
  - brew update
  - brew install yaml-cpp
  - brew install boost
  - brew install lua

install: pip install codecov

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_success: codecov

os: osx
